namePrefix: staging-
commonLabels:
  variant: staging
commonAnnotations:
  note: Hello, I am running in staging environment!
namespace: staging
bases:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
resources:
- namespace.yaml
images:
- name: dennydgl1/java-hello-world
  newName: dennydgl1/java-hello-world
  newTag: "2.1"
configMapGenerator:
 - behavior: merge
   name: java-hello-world-cm
   envs: 
    - env.properties
   files:
    - application.yaml 
