namePrefix: production-
commonLabels:
  variant: production
commonAnnotations:
  note: Hello, I am running in production environment!
namespace: production
bases:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
resources:
- namespace.yaml
- ingress.yaml
images:
- name: dennydgl1/java-hello-world
  newName: dennydgl1/java-hello-world
  newTag: "2.0"
configMapGenerator:
 - behavior: merge
   name: java-hello-world-cm
   envs: 
    - env.properties
   files:
    - application.yaml 
